# Node 이미지를 기반으로 설정
FROM node:18

# 작업 디렉터리 설정
WORKDIR /app

# 필요한 종속성을 설치합니다.
COPY ./fe/package.json ./fe/package-lock.json ./
WORKDIR /app/fe
RUN npm install # 프로젝트의 종속성 설치
WORKDIR /app

# 빌드된 결과물을 이미지에 복사
COPY ./fe/dist ./

# 필요한 경우 실행 명령어 설정 (예: 간단한 서버 실행)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
